### ISSUE TITLE
Show me the code - Sprint 1

### ISSUE THREAD

**Issue by Mylena-angelica** [Mylena-angelica/Debian-GCES-24.1#1]
Atualizações sobre o show me the code da primeira Sprint

**Comment by Mylena-angelica** [comment]
@leonardogonmac Minhas tarefas dessa Sprint. Agradeço a ajuda na apresentação. 

# Aqui está um resumo das minhas contribuições até o momento:

## Contribuição com a Wiki do Debian BSB:

Atualizei e melhorei a documentação da wiki do Debian BSB, tornando as informações mais acessíveis e úteis para outros desenvolvedores e usuários.

## Empacotamento

Concluí o empacotamento de três pacotes, sendo um em Python e dois em Ruby e estou trabalhando em um 4 pacote. 

### Ruby-airbrussh 

Minha primeira contribuição já foi revisada, deu merge com a main do projeto e adicionado à versão tester do Debian.
Foi feita uma atualização upstream. 

Link tracker: https://tracker.debian.org/pkg/ruby-airbrussh

### python-shodan

Foi feita uma atualização upstream.  Contribuição já foi revisada, deu merge com a main do projeto e adicionado à versão tester  do Debian.

Link tracker: https://tracker.debian.org/pkg/python-shodan

## hiera

Foi feita uma atualização upstream e adição de patches.  Contribuição já foi revisada, deu merge com a main do projeto e adicionado à versão tester  do Debian.

Link tracker: https://tracker.debian.org/pkg/hiera

## golang-github-vjeantet-grok

Empacotamento em andamento, será feito atualização upstream e uma parte de QA

Link tracker: https://tracker.debian.org/pkg/golang-github-vjeantet-grok
Link issue: https://salsa.debian.org/debian-brasilia-team/docs/-/issues/225

**Comment by luanasoares0901** [comment]
Apresentação realizada, issue fechada
