### ISSUE TITLE
sprint 4 - Ana

### ISSUE THREAD

**Issue by analuizargds** [Mylena-angelica/Debian-GCES-24.1#31]
### Link do Tracker
[Tracker do Pacote](https://tracker.debian.org/pkg/<nome_do_pacote>)

### Link do Salsa
[Salsa do Projeto](https://salsa.debian.org/...)

### Link do Lintian
[Lintian do Pacote](https://udd.debian.org/lintian/?packages=<nome_do_pacote>)

**Comment by Mylena-angelica** [comment]
Fechando. Sprint já acabou.
