### ISSUE TITLE
Sprint 4 Luana

### ISSUE THREAD

**Issue by luanasoares0901** [Mylena-angelica/Debian-GCES-24.1#35]
## prometheus-flask-exporter

O Prometheus-flask-exporter é uma ferramenta que facilita a integração de métricas do Prometheus em aplicações web baseadas no Flask. Ele fornece uma maneira simples de exportar métricas de desempenho e estado de uma aplicação Flask para o Prometheus, um sistema de monitoramento e alertas popular. 

### Alterações

As alterações realizadas foram a de subir uma nova versão upstream e atualizar o standards-version

![image](https://github.com/user-attachments/assets/a4810ed1-653f-4af0-b928-69599a09a3bf)

### Link do Tracker
[Tracker do Pacote](https://tracker.debian.org/pkg/prometheus-flask-exporter)

### Link do Salsa
[Salsa do Projeto](https://salsa.debian.org/python-team/packages/prometheus-flask-exporter.git)

### Link do Lintian
[Lintian do Pacote](https://udd.debian.org/lintian/?packages=prometheus-flask-exporter)

![image](https://github.com/user-attachments/assets/52c84851-ec3f-42ea-9406-df60698f899a)

**Comment by luanasoares0901** [comment]
Além dessa atividade de empacotamento, foram realizadas as seguintes atividades:

- Correções necessárias dos últimos pacotes, dividindo os commits e mudando a branch do merge request
- Adição de conteúdo ao tutorial desenolvido pelo grupo

**Comment by Mylena-angelica** [comment]
Fechando. Sprint já acabou.
