### ISSUE TITLE
Pacotes Luana - Sprint 2

### ISSUE THREAD

**Issue by luanasoares0901** [Mylena-angelica/Debian-GCES-24.1#6]
Aqui serão adicionados os pacotes em que trabalharei na Sprint 2

- Subliminal - https://tracker.debian.org/pkg/subliminal

**Comment by luanasoares0901** [comment]
## Subliminal
### nova versão upstream
Subliminal é uma ferramenta utilizada na linha de comando para buscar e baixar legendas.

![sub1](https://github.com/user-attachments/assets/6fdf8289-43ee-400e-80ed-4c3821af9136)

<br> [Link issue no Salsa](https://salsa.debian.org/debian-brasilia-team/docs/-/issues/260)

<br> [Link do respositório no salsa](https://salsa.debian.org/python-team/packages/subliminal)

<br> [Link do Tracker](https://tracker.debian.org/pkg/subliminal)

<br> [Link para o Lintian](https://udd.debian.org/lintian/?packages=subliminal)

![sub2](https://github.com/user-attachments/assets/8781a1dd-578c-4442-86f7-2bef5b96c585)


### Empacotamento

Nesta issue foi realizada a atualização para a nova versão upstream e atualização do watch para uma nova versão.

![sub3](https://github.com/user-attachments/assets/3224b38f-e7cf-4d81-93e1-dc8209bd0e9f)

**Comment by Mylena-angelica** [comment]
Merge com a main feito
