### ISSUE TITLE
Template para Issues

### ISSUE THREAD

**Issue by HenriPucci** [Mylena-angelica/Debian-GCES-24.1#8]
Adicionar um template para as issues que serão feitas.

**Comment by HenriPucci** [comment]
## Nome do Pacote

### Link do Tracker
[Tracker do Pacote](https://tracker.debian.org/pkg/<nome_do_pacote>)

### Link do Salsa
[Salsa do Projeto](https://salsa.debian.org/...)

### Bugs Relacionados


### Link do Lintian
[Lintian do Pacote](https://udd.debian.org/lintian/?packages=<nome_do_pacote>)

### Descrição


### Problemas Conhecidos


### Observações Adicionais

**Comment by Mylena-angelica** [comment]
Feito
